version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agan_cc_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: agan_cc_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
    ports:
      - "3306:3306"
    volumes:
      - db_datas:/var/lib/mysql

volumes:
  db_datas:
